plugins {
    id 'forgegradle' version '4.1.0'
    id 'org.spongepowered.mixin' version '0.13.0'
}

minecraft {
    version = '1.14.4'
    mappings = 'official_1.14.4'
}

dependencies {
    modImplementation 'net.minecraftforge:forge:1.14.4-28.2.0'
}

mixin {
    refmap = 'refmap.json'
    accessTransformer = 'accessTransformer.json'
}